name = "brushtail-digital"
main = "api/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

route = { pattern = "api.brushtail.digital", custom_domain = true }

[vars]
CORS_ORIGIN = "https://brushtail.digital"
